author = "kylegoetz"
description = "Unison for Lapce: powered by ucm"
display-name = "Unison (ucm)"
name = "lapce-unison-ucm"
version = "1.0.0"
wasm = "bin/lapce-unison-ucm.wasm"

[activation]
language = ["unison"] # or "u"?
workspace-contains = [
  "*/*.u",
]

[config."volt.serverPath"]
default = ""
description = "Path to ucm"
